jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu 16.04'
  variables:
    buildConfiguration: 'Release'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Linux Build'
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    buildConfiguration: 'Release'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Windows Build'
